dispMUA.arDispMUAAllocation["u"] =
{
  "ultimate-auction.de" : [ "ultimate-auction_de.png" , "http://www.ultimate-auction.de/" ] ,
  "ubuntu thunderbird" : [ "thunderbird.png" , "http://www.ubuntu.com/" ] ,
  "userland frontier" : [ "userland_frontier.png" ] ,
  "usanet web-mailer" : [ "usanet.png" , "http://www.usa.net/" ] ,
  "ultrafunk popcorn" : [ "popcorn.png" , "http://www.ultrafunk.com/products/popcorn/" ] ,
  "usenet explorer" : [ "usenet_explorer.png" , "http://www.usenetexplorer.com/" ] ,
  "umo mail system" : [ "mozilla_update.png" , "http://update.mozilla.org/" ] ,
  "upcdata.info" : [ "upcdata.png" , "http://upcdata.info/" ] ,
  "uta-webmail" : [ "utanet.png" , "http://www.utanet.at/" ] ,
  "unknown sub" : [ "aol.png" , "http://www.aol.com/" ] ,
  "unknown (no" : [ "aol.png" , "http://www.aol.com/" ] ,
  "ubb.threads" : [ "ubbthreads.png" , "http://www.ubbcentral.com/" ] ,
  "ux systems" : [ "ux-systems.png" , "http://www.ux.pl/" ] ,
  "utstarcom" : [ "vonage.png" , "http://www.vonage.com/" ] ,
  "unitymail" : [ "unity_mail.png" , "http://www.messagemedia.com/" ] ,
  "uebimiau" : [ "uebimail.png" , "http://www.uebimiau.org/" ] ,
  "ubiqmail" : [ "ubiqmail.png" , "http://yournet.freebit.net/ubiqmail/scheme/" ] ,
  "usermin" : [ "usermin.png" , "http://www.webmin.com/usermin.html" ] ,
  "usenext" : [ "usenext.png" , "http://usenext.en.softonic.com/" ] ,
  "umailng" : [ "umailng.png" ] ,
  "ukr.net" : [ "ukr_net.png" , "http://www.ukr.net/" ] ,
  "userve" : [ "userve.png" ] ,
  "unisys" : [ "unisys.png" , "http://www.unisys.com/" ] ,
  "unison" : [ "unison.png" , "http://www.panic.com/unison/" ] ,
  "unanet" : [ "unanet.png" , "http://www.unanet.com/" ] ,
  "uacett" : [ "toshiba.png" , "http://www.estudio.com.sg/" ] ,
  "ucoz" : [ "ucoz.png" , "http://www.ucoz.com/" ] ,
  "u <" : [ "umail.png" , "http://www.umail.ucsb.edu/" ] ,
}
