dispMUA.arDispMUAAllocation["v"] =
{
  "voltimum newsletter-mailer" : [ "voltimum.png" , "http://www.voltimum.de/" ] ,
  "venere net spa mailer" : [ "venere.png" , "http://www.venere.com/" ] ,
  "virtek mail systems" : [ "virtek.png" , "http://www.virtek.com/" ] ,
  "visualsoft mailer" : [ "visualsoft.png" ] ,
  "visnetic mailflow" : [ "visnetic_mailflow.png" , "http://www.deerfield.com/Products/VisNetic-MailFlow/" ] ,
  "volny.cz webmail" : [ "volny_cz.png" , "http://web.volny.cz/" ] ,
  "visnetic webmail" : [ "visnetic_mailserver.png" , "http://www.deerfield.com/Products/VisNetic-MailServer/web_mail/" ] ,
  "vernunft schweiz" : [ "vernunft_schweiz.png" , "http://www.vernunft-schweiz.ch/" ] ,
  "visual paradigm" : [ "visual-paradigm.png" , "http://www.visual-paradigm.com/" ] ,
  "vallen e-mailer" : [ "vallen.png" , "http://www.vallen.de/freeware/index.html#Vallen%20e-Mailer" ] ,
  "virtual target" : [ "virtualtarget.png" , "http://www.virtualtarget.com.br/" ] ,
  "virtual access" : [ "virtual_access.png" , "http://www.virtual-access.org/" ] ,
  "vas-hosting.cz" : [ "vas-hosting_cz.png" , "http://www.vas-hosting.cz/" ] ,
  "veritas smtp" : [ "veritas.png" , "http://www.symantec.com/redirects/veritas/veritas_com" ] ,
  "vivian mail" : [ "vivian_mail.png" , "http://www.deepsleep.de/software/vivianmail/vivianmail.html" ] ,
  "vplan plus" : [ "vplan-plus.png" , "http://vplan.svenkan.bplaced.de/vplan.php?action=plus" ] ,
  "vizslamail" : [ "vizslamail.png" , "http://www.vizslamail.hu/" ] ,
  "versamail" : [ "versamail.png" , "http://www.palm.com/us/support/accessories/versamail/" ] ,
  "veluxmail" : [ "velux.png" , "http://velux.de/" ] ,
  "vbulletin" : [ "vbulletin.png" , "http://www.vbulletin.com/" ] ,
  "vacation/" : [ "vacation.png" , "http://www.csamuel.org/software/vacation" ] ,
  "v-webmail" : [ "v-webmail.png" , "http://v-webmail.sourceforge.net/" ] ,
  "vodafone" : [ "vodafone.png" , "http://www.vodafone.de/" ] ,
  "vista.pl" : [ "vista_pl.png" , "http://www.vista.pl/" ] ,
  "vboxmail" : [ "vbox.png" , "http://smarden.org/pape/vbox3/" ] ,
  "voyager" : [ "voyager.png" , "http://www.ritlabs.com/de/products/voyager/" ] ,
  "voxmail" : [ "voxmail.png" , "http://voxmail.sourceforge.net/" ] ,
  "vipmail" : [ "vipmail.png" , "http://vipmail.hu/" ] ,
  "verizon" : [ "verizon.png" , "http://www.verizon.net/" ] ,
  "viadeo" : [ "viadeo.png" , "http://www.viadeo.com/" ] ,
  "vsoup" : [ "vsoup.png" , "http://www.mardys.de/vsoup.htm" ] ,
  "vkpmx" : [ "pragmamx.png" , "http://www.pragmamx.org/" ] ,
  "vwar" : [ "vwar.png" , "http://www.vwar.de/" ] ,
  "vhcs" : [ "vhcs.png" , "http://www.vhcs.net/" ] ,
  "vm5." : [ "emacs.png" , "http://www.gnu.org/software/emacs/" ] ,
  "vm " : [ "emacs.png" , "http://www.gnu.org/software/emacs/" ] ,
}
