dispMUA.arDispMUAAllocation["q"] =
{
  "qualcomm macintosh classic eudora" : [ "eudora.png" , "http://www.eudora.com/" ] ,
  "qualcomm macos classic eudora" : [ "eudora.png" , "http://www.eudora.com/" ] ,
  "qualcomm windows eudora" : [ "eudora.png" , "http://www.eudora.com/" ] ,
  "qualcomm macos x eudora" : [ "eudora.png" , "http://www.eudora.com/" ] ,
  "qusnetsoft newsreader" : [ "qusnetsoft_newsreader.png" , "http://www.qusnetsoft.ru/" ] ,
  "quality web email" : [ "netwinsite.png" , "http://www.netwinsite.com/webmail/" ] ,
  "quotient q.tools" : [ "quotient_qtools.png" , "http://www.quotientmarketing.com/qtools_defined.aspx" ] ,
  "quickmail pro" : [ "quickmail-pro.png" , "http://www.outspring.com/index.php?option=com_content&task=view&id=69" ] ,
  "qualisite cms" : [ "qualisite_de.png" , "http://www.qualisite.de/" ] ,
  "qsc's mailler" : [ "qsc.png" , "http://www.qsc.de/" ] ,
  "qa webaccess" : [ "qaconsulting.png" , "http://www.qaconsulting.com.br/" ] ,
  "quickmail" : [ "quickmail.png" , "http://www.outspring.com/index.php?option=com_content&task=view&id=70" ] ,
  "qps.qmail" : [ "python.png" , "http://pypi.python.org/pypi/QPS/" ] ,
  "queplix" : [ "queplix.png" , "http://www.queplix.com/" ] ,
  "quilt/" : [ "quilt.png" , "http://savannah.nongnu.org/projects/quilt" ] ,
  "qqmail" : [ "qqmail.png" , "http://www.umailcampaign.com/mailcom.aspx" ] ,
  "qmail" : [ "qmail.png" , "http://www.qmail.org/" ] ,
}
