dispMUA.arDispMUAAllocation["t"] =
{
  "touchpoint campaign manager" : [ "touchpoint.png" , "http://www.touchpoint.co.nz/products/campaign.html" ] ,
  "tva e-mail transfer client" : [ "tva.png" ] ,
  "tu-dortmund wsmailer" : [ "tu-dortmund.png" , "http://www.uni-dortmund.de/" ] ,
  "the mailman replybot" : [ "mailman.png" , "http://www.list.org/" ] ,
  "the polarbar mailer" : [ "polarbar.png" , "http://www.polarbar.net/" ] ,
  "tcl email library" : [ "tcl.png" , "http://web.uvic.ca/~erempel/tcl/Email/Email.html" ] ,
  "tabs laboratories" : [ "tabslab.png" , "http://www.tabslab.com/" ] ,
  "tricorn autobahn" : [ "autobahn.png" , "http://www.tricorn.net/" ] ,
  "talktalk webmail" : [ "aol_talktalk.png" , "http://info.aol.co.uk/talktalk-webmail/" ] ,
  "talisma netagent" : [ "talisma.png" , "http://www.talisma.com/" ] ,
  "triera internet" : [ "triera.png" , "http://www.triera.net/" ] ,
  "thingamajob.com" : [ "thingamajob_com.png" , "http://www.thingamajob.com/" ] ,
  "the codeweavers" : [ "codeweavers.png" , "http://www.codeweavers.com/" ] ,
  "tsworks e-mail" : [ "tsworks.png" , "http://www.fujitsu.com/" ] ,
  "thinkui mailer" : [ "thinkui_com.png" , "http://www.thinkui.com/" ] ,
  "testtrack smtp" : [ "testtrack.png" , "http://www.seapine.com/ttpro.html" ] ,
  "tvnet e-pasts" : [ "tvnet_lv.png" , "http://www.tvnet.lv/" ] ,
  "tripolis mail" : [ "tripolis.png" , "http://www.tripolis.com/" ] ,
  "triggermailer" : [ "triggermail.png" , "http://sailthru.com/products/triggermail" ] ,
  "tweakers.net" : [ "tweakers_net.png" , "http://www.tweakers.net/" ] ,
  "tutorials.de" : [ "tutorials_de.png" , "http://www.tutorials.de/" ] ,
  "tibet server" : [ "tibetserver.png" , "http://www.tibetserver.com/" ] ,
  "thindata ems" : [ "thindata_ems.png" , "http://www.thindata.com/" ] ,
  "talisma mail" : [ "talisma.png" , "http://www.talisma.com/" ] ,
  "turbomailer" : [ "turbomailer.png" , "http://www.xellsoft.com/TurboMailer.html" ] ,
  "thunderbird" : [ "thunderbird.png" , "http://www.mozilla.com/thunderbird/" ] ,
  "team noggin" : [ "noggin.png" , "http://www.noggin.com.au/products/gateway" ] ,
  "tuonome.it" : [ "tuonome_it.png" , "http://www.tuonome.it/" ] ,
  "tripitmail" : [ "tripit_com.png" , "http://www.tripit.com/" ] ,
  "tmcnet.com" : [ "tmcnet_com.png" , "http://www.tmcnet.com/" ] ,
  "tdc online" : [ "tdc.png" , "http://tdconline.dk/" ] ,
  "targetmail" : [ "techtarget.png" , "http://www.techtarget.com/" ] ,
  "turbomail" : [ "turbomail.png" , "http://www.python-turbomail.org/" ] ,
  "trademail" : [ "fumasoft.png" , "http://www.fumasoft.com/" ] ,
  "torba.com" : [ "torba.png" , "http://torba.com/" ] ,
  "tellmatic" : [ "tellmatic.png" , "http://tellmatic.org/" ] ,
  "tapirmail" : [ "tapirmail.png" , "http://www.flypig.co.uk/tapirmail/" ] ,
  "tapetrack" : [ "tapetrack.png" , "http://www.tapetrack.com/" ] ,
  "turukame" : [ "turukame.png" ] ,
  "turnpike" : [ "turnpike.png" , "http://www.turnpike.com/" ] ,
  "tugnews/" : [ "tu-graz.png" , "http://webnews.tugraz.at/" ] ,
  "trialpay" : [ "trialpay.png" , "http://www.trialpay.com/" ] ,
  "the bat!" : [ "the_bat.png" , "http://www.ritlabs.com/en/products/thebat/" ] ,
  "telebyte" : [ "telebyte.png" , "http://webmail.telebyte.nl/" ] ,
  "teamware" : [ "fujitsu.png" , "http://software.fujitsu.com/jp/teamware/" ] ,
  "t-online" : [ "t-online.png" , "http://www.t-online.de/" ] ,
  "tvnmail" : [ "tvnmail.png" , "http://www.tvn.hu/" ] ,
  "toshiba" : [ "toshiba.png" , "http://www.toshiba.co.jp/" ] ,
  "topdesk" : [ "topdesk.png" , "http://www.topdesk.com/" ] ,
  "the bee" : [ "the-bee.png" , "http://www.avtlab.ru/thebee.htm" ] ,
  "tactica" : [ "tactica.png" , "http://www.tacticasoft.com/" ] ,
  "t-gnus/" : [ "gnus.png" , "http://gnus.org/" ] ,
  "try.hu" : [ "try_hu.png" , "http://www.try.hu/" ] ,
  "tralix" : [ "tralix.png" , "http://www.tralix.com/" ] ,
  "totemo" : [ "totemo.png" , "http://www.totemo.ch/" ] ,
  "tchibo" : [ "tchibo.png" , "http://www.tchibo.com/" ] ,
  "tal.de" : [ "tal_de.png" , "http://www.tal.de/" ] ,
  "typo3" : [ "typo3.png" , "http://www.typo3.com/" ] ,
  "topix" : [ "topix.png" , "http://www.topix.de/" ] ,
  "thoth" : [ "thoth.png" , "http://home.earthlink.net/~thoth-help/thoth.html" ] ,
  "thor " : [ "thor.png" , "http://www.thule.no/" ] ,
  "telix" : [ "telix.png" , "http://www.telix.com/delta/products/" ] ,
  "twig" : [ "twig.png" , "http://informationgateway.org/" ] ,
  "trn " : [ "trn.png" , "http://treekom.ftml.net/" ] ,
  "trac" : [ "trac.png" , "http://trac.edgewall.org/" ] ,
  "tin/" : [ "tin.png" , "http://www.tin.org/" ] ,
  "tin " : [ "tin.png" , "http://www.tin.org/" ] ,
  "tigo" : [ "tigo.png" , "http://www.tigo.com.sv/" ] ,
  "toi" : [ "t-online.png" , "http://www.t-online.de/" ] ,
  "tt " : [ "tt.png" , "http://www.icosaedro.it/tt/" ] ,
}
