dispMUA.arDispMUAAllocation["m"] =
{
  "mailer by oracle utl_smtp - used by psu foundation" : [ "psufmailer.png" , "http://www.foundation.pdx.edu/" ] ,
  "multi box - interfejs www poczty orange.pl" : [ "orange.png" , "http://www.orange.pl/" , "orange.pl" ] ,
  "messagerie internet de microsoft/mapi" : [ "ms_patch.png" , "http://www.microsoft.com/" ] ,
  "marshallsoft smtp/pop3 email engine" : [ "marshallsoft.png" , "http://www.marshallsoft.com/products.htm" ] ,
  "mailer kundenservice - kabel bw" : [ "kabel-bw.png" , "http://www.kabelbw.de/" ] ,
  "microsoft internet-e-post/mapi" : [ "ms_patch.png" , "http://www.microsoft.com/" ] ,
  "microsoft windows live mail" : [ "ms_live.png" , "http://www.microsoft.com/" ] ,
  "microsoft office outlook 12" : [ "ms_outlook12.png" , "http://www.microsoft.com/" ] ,
  "microdec plc - profile rpm" : [ "microdec-rpm.png" , "http://www.microdec-profile.com/" ] ,
  "mailform (www.mailform.cz)" : [ "mailform.png" , "http://www.mailform.cz/" ] ,
  "mailer @ standleitungen.de" : [ "standleitungen_de.png" , "http://www.standleitungen.de/" ] ,
  "mail, http://www.czebra.de" : [ "czebra_de.png" , "http://www.czebra.de/" ] ,
  "microsoft-outlook-express" : [ "ms_outlook_express.png" , "http://www.microsoft.com/" ] ,
  "microsoft outlook express" : [ "ms_outlook_express.png" , "http://www.microsoft.com/" ] ,
  "microsoft internet e-mail" : [ "ms_patch.png" , "http://www.microsoft.com/" ] ,
  "microsoft exchange server" : [ "ms_exchange.png" , "http://www.microsoft.com/" ] ,
  "microsoft avondale mailer" : [ "microsoft.png" , "http://www.microsoft.com/" ] ,
  "mailer powered by 1do1.pl" : [ "1do1_pl.png" , "http://1do1.pl/" ] ,
  "microsoft office outlook" : [ "ms_outlook.png" , "http://www.microsoft.com/" ] ,
  "microsoft internet mail" : [ "ms_patch.png" , "http://www.microsoft.com/" ] ,
  "mailing services by eid" : [ "eid.png" , "http://www.eid.nl/" ] ,
  "mail sent with web2life" : [ "web2life.png" , "http://www.web2life.de/" ] ,
  "microsoft windows mail" : [ "ms_mail.png" , "http://www.microsoft.com/" ] ,
  "microsoft-windows-mail" : [ "ms_mail.png" , "http://www.microsoft.com/" ] ,
  "mws mass mailing news" : [ "massmailingnews.png" , "http://www.massmailingnews.com/" ] ,
  "mr/2 internet cruiser" : [ "mr2.png" , "http://www.mr2ice.com/" ] ,
  "mmm execution manager" : [ "zoomio.png" , "http://www.zoomio.com/" ] ,
  "messagefocus launcher" : [ "adestra_co_uk.png" , "http://www.adestra.co.uk/" ] ,
  "mainsail mail service" : [ "mainsail.png" , "http://www.mainsail.com/" ] ,
  "mailer at germany.ru" : [ "germany_ru.png" , "http://www.germany.ru/" ] ,
  "mozilla-thunderbird" : [ "thunderbird.png" , "http://www.mozilla.com/thunderbird/" ] ,
  "mozilla thunderbird" : [ "thunderbird.png" , "http://www.mozilla.com/thunderbird/" ] ,
  "minismtp (javamail)" : [ "intrasoft.png" , "http://www.intrasoft-intl.com/" ] ,
  "microsoft-entourage" : [ "ms_entourage.png" , "http://www.microsoft.com/" ] ,
  "microplanet-gravity" : [ "microplanet.png" , "http://mpgravity.sourceforge.net/" ] ,
  "microplanet gravity" : [ "microplanet.png" , "http://mpgravity.sourceforge.net/" ] ,
  "messagingengine.com" : [ "messagingengine.png" , "http://www.messagingengine.com/" ] ,
  "maillist controller" : [ "amlc.png" , "http://www.arclab.com/products/amlc/" ] ,
  "mail (gnu mailutils" : [ "gnu.png" , "http://www.gnu.org/software/mailutils/" ] ,
  "mypersonality.info" : [ "mypersonality.png" , "http://www.mypersonality.info/" ] ,
  "mobildiscounter.de" : [ "mobildiscounter_de.png" , "http://www.mobildiscounter.de/" ] ,
  "microsoft exchange" : [ "ms_exchange.png" , "http://www.microsoft.com/" ] ,
  "mrs internet mail" : [ "cycos.png" , "http://www2.cycos.com/products-solutions/cycos-mrs.html" ] ,
  "microsoft outlook" : [ "ms_outlook.png" , "http://www.microsoft.com/" ] ,
  "mail user's shell" : [ "mush.png" , "http://www.well.com/user/barts/mush.html" ] ,
  "my own hands[tm]" : [ "cweiske.png" , "http://cweiske.de/" ] ,
  "mp form mail cgi" : [ "futomi.png" , "http://www.futomi.com/" ] ,
  "mh dialog server" : [ "mh_dialog.png" , "http://www.millionhandshakes.com/" ] ,
  "mailsite express" : [ "mailsite_express.png" , "http://www.mailsite.com/products/express-webmail-server.asp" ] ,
  "mails.at webmail" : [ "mails_at.png" , "http://www.mails.at/" ] ,
  "mailer by oracle" : [ "oracle.png" , "http://www.oracle.com/" ] ,
  "mailed by oracle" : [ "oracle.png" , "http://www.oracle.com/" ] ,
  "mailcity service" : [ "lycos-mailcity.png" , "http://www.mailcity.com/" ] ,
  "mailchimp mailer" : [ "mailchimp.png" , "http://www.mailchimp.com/" ] ,
  "mail/news client" : [ "thunderbird.png" , "http://www.mozilla.com/thunderbird/" ] ,
  "mail distributor" : [ "mail-distributor.png" , "http://www.woodensoldier.info/soft/md.htm" ] ,
  "macintosh eudora" : [ "eudora.png" , "http://www.eudora.com/" ] ,
  "mynet webmailer" : [ "mynet.png" ] ,
  "mark/space mail" : [ "markspacemail.png" ] ,
  "mapsolute map24" : [ "map24.png" , "http://www.map24.com/" ] ,
  "mailer_avast.ru" : [ "avast.png" , "http://www.avast.ru/" ] ,
  "mail (mailutils" : [ "gnu.png" , "http://www.gnu.org/software/mailutils/" ] ,
  "mt-newswatcher" : [ "mt-newswatcher.png" , "http://www.smfr.org/mtnw/" ] ,
  "mmd eci mailer" : [ "ieci.png" , "http://www.ieci.es/" ] ,
  "mithi-web-mail" : [ "mithi-web-mail.png" , "http://www.mithi.com/" ] ,
  "message editor" : [ "messageeditor.png" ] ,
  "mandic:webmail" : [ "mandic.png" , "http://www.mandic.com.br/" ] ,
  "mailreader.com" : [ "mailreader.png" , "http://www.mailreader.com/" ] ,
  "mynayoki-mail" : [ "nayoki.png" , "http://www.nayoki.de/" ] ,
  "mymail-in.net" : [ "mymail-in_net.png" , "http://mymail-in.net/" ] ,
  "mpop web-mail" : [ "mail_ru.png" , "http://www.mail.ru/" ] ,
  "mobile office" : [ "telenor.png" , "http://www.telenor.com/" ] ,
  "mimemailxphp4" : [ "php.png" , "http://www.feike.biz/php_mime_mail_de.html" ] ,
  "microsoft cdo" : [ "ms_cdo.png" , "http://www.microsoft.com/" ] ,
  "messenger-pro" : [ "messenger-pro.png" , "http://www.arsvcs.demon.co.uk/r-comp/messpro/" ] ,
  "maillist king" : [ "maillist_king.png" , "http://www.xequte.com/maillistking/" ] ,
  "mail explorer" : [ "mailexplorer.png" , "http://member.nifty.ne.jp/miyaishi/" ] ,
  "mach 5 mailer" : [ "m5_mailer.png" , "http://www.mach5.com/products/mailer/" ] ,
  "minerva mail" : [ "minervamail.png" , "http://www.minervamail.com/" ] ,
  "mikini media" : [ "mikinimedia.png" , "http://www.mikinimedia.de/" ] ,
  "messenger v1" : [ "messenger-pro.png" , "http://www.intellegit.com/software/messenger/" ] ,
  "max e-mailer" : [ "max_e-mailer.png" , "http://ismax.com/" ] ,
  "materiel.net" : [ "materiel_net.png" , "http://www.materiel.net/" ] ,
  "match mailer" : [ "match_com.png" , "http://www.match.com/" ] ,
  "mailmagicpro" : [ "mailmagic.png" , "http://en.infinisys.co.jp/product/mail_magic_pro/" ] ,
  "mail::mailer" : [ "perl.png" , "http://search.cpan.org/dist/MailTools/" ] ,
  "mach5 mailer" : [ "m5_mailer.png" , "http://www.mach5.com/products/mailer/" ] ,
  "m5mailer.com" : [ "m5_mailer.png" , "http://www.mach5.com/products/mailer/" ] ,
  "mybb mailer" : [ "mybb_mailer.png" , "http://mybb.ru/" ] ,
  "mondo media" : [ "mondo-media.png" , "http://www.mondo-media.de/" ] ,
  "microdot-ii" : [ "microdot.png" , "http://www.vapor.com/md2/" ] ,
  "mercury mts" : [ "mercury.png" , "http://www.pmail.com/overviews/ovw_mercury.htm" ] ,
  "memotoo.com" : [ "memotoo.png" , "http://www.memotoo.com/" ] ,
  "melin email" : [ "melin_email.png" , "http://www.melin.eu/" ] ,
  "melcast.com" : [ "melcast.png" , "http://www.melcast.com/" ] ,
  "mediag3.com" : [ "mediag3_com.png" , "http://www.mediag3.com/" ] ,
  "measuremail" : [ "measuremail.png" , "http://www.measuremail.nl/" ] ,
  "mandic:zeus" : [ "mandic-zeus.png" , "http://www.mandic.com.br/" ] ,
  "mailsender " : [ "mailsender.png" , "http://www.mailsender.com.br/" ] ,
  "mailingwork" : [ "mailingwork.png" , "http://www.mailingwork.de/" ] ,
  "mailintouch" : [ "mailintouch.png" , "http://www.mailingtouch.com/" ] ,
  "mailenstein" : [ "mailenstein_de.png" , "http://www.mailenstein.de/" ] ,
  "mailcleaner" : [ "mailcleaner.png" , "http://www.mailcleaner.net/" ] ,
  "mail bomber" : [ "mail-bomber.png" , "http://www.softheap.com/bomber.html" ] ,
  "mag-news-g4" : [ "magnews.png" , "http://www.mag-news.it/" ] ,
  "mail-rakete" : [ "mailrakete.png" , "http://www.mailrakete.de/" ] ,
  "myibay.com" : [ "myibay_com.png" , "http://www.myibay.com/" ] ,
  "mwbusiness" : [ "mwbusiness.png" , "http://www.mwbusiness.org/" ] ,
  "mondo shop" : [ "mondo-media.png" , "http://www.mondo-media.de/" ] ,
  "modernbill" : [ "parallels.png" , "http://www.modernbill.com/" ] ,
  "mintersoft" : [ "mintersoft.png" , "http://www.mintersoft.com/" ] ,
  "mime::lite" : [ "perl.png" , "http://search.cpan.org/dist/MIME-Lite/" ] ,
  "mime-tools" : [ "perl.png" , "http://search.cpan.org/dist/MIME-tools/" ] ,
  "mercury/32" : [ "mercury.png" , "http://www.pmail.com/overviews/ovw_mercury.htm" ] ,
  "max mailer" : [ "maxbulk.png" , "http://www.maxprog.com/maxbulk.html" ] ,
  "mailweaver" : [ "mailweaver.png" , "http://www.mailweaver.ch/" ] ,
  "mailprimer" : [ "mailprimer.png" , "http://www.mailprimer.com/" ] ,
  "mailengine" : [ "lyris.png" , "http://www.lyris.com/software/mailengine/" ] ,
  "mailenable" : [ "mailenable.png" , "http://www.mailenable.com/" ] ,
  "maildirect" : [ "maildirect.png" , "http://maildirect.co.in/" ] ,
  "maildivide" : [ "maildivide.png" , "http://homepage3.nifty.com/efs/MailDividef.html" ] ,
  "mailcasino" : [ "grandcasino.png" , "http://www.grand-casino.com/" ] ,
  "mailanyone" : [ "fusemail.png" , "http://www.fusemail.com/" ] ,
  "mail::send" : [ "perl.png" , "http://search.cpan.org/dist/MailTools/" ] ,
  "mail/haiku" : [ "haiku.png" , "http://www.haiku-os.org/" ] ,
  "mail.zp.ua" : [ "mail_zp_ua.png" , "http://mail.zp.ua/" ] ,
  "magnews-g4" : [ "magnews.png" , "http://www.mag-news.it/" ] ,
  "maggi mail" : [ "maggi.png" , "http://www.maggi.de/" ] ,
  "m-acquaint" : [ "m-acquaint.png" , "http://www.macquaint.com/" ] ,
  "mymailout" : [ "mymailout.png" , "http://www.mymailout.com/" ] ,
  "mymail.ch" : [ "mymail_ch.png" , "http://www.mymail.ch/" ] ,
  "movixmail" : [ "movixmail.png" , "http://www.movix.com.br/" ] ,
  "mojo mail" : [ "mojo_mail.png" , "http://mojo.skazat.com/" ] ,
  "mm3-email" : [ "mm3tools.png" , "http://www.mm3tools.de/" ] ,
  "mirapoint" : [ "mirapoint.png" , "http://www.mirapoint.com/" ] ,
  "metamail/" : [ "metamail.png" , "http://www.meta.ua/" ] ,
  "messenger" : [ "messenger.png" , "http://mailnews.netscape.com/releases" ] ,
  "merlin.pl" : [ "merlin_pl.png" , "http://merlin.pl/" ] ,
  "mediaworx" : [ "mediaworx.png" , "http://www.mediaworx.com/" ] ,
  "mediawiki" : [ "mediawiki.png" , "http://www.mediawiki.org/" ] ,
  "mediatrix" : [ "mediatrix.png" , "http://www.ityx-solutions.de/" ] ,
  "medi@trix" : [ "mediatrix.png" , "http://www.ityx-solutions.de/" ] ,
  "matchbox/" : [ "plumdigitalmedia.png" , "http://matchbox.plumdigitalmedia.com/" ] ,
  "mallux.de" : [ "mallux_de.png" , "http://www.mallux.de/" ] ,
  "majordomo" : [ "greatcircle.png" , "http://www.greatcircle.com/majordomo/" ] ,
  "mailmagic" : [ "mailmagic.png" , "http://en.infinisys.co.jp/product/mail_magic/" ] ,
  "mailboxer" : [ "mailboxer.png" , "http://iungo.org/products/MailBoxer" ] ,
  "magicmail" : [ "magicmail.png" , "http://magicmail.linuxmagic.com/" ] ,
  "mailsmith" : [ "mailsmith.png" , "http://www.barebones.com/products/mailsmith/" ] ,
  "mail/news" : [ "thunderbird.png" , "http://www.mozilla.com/thunderbird/" ] ,
  "magnewsg4" : [ "magnews.png" , "http://www.mag-news.it/" ] ,
  "mymailer" : [ "mymailer.png" , "http://www.l-to.de/" ] ,
  "mulberry" : [ "mulberry.png" , "http://www.mulberrymail.com/" ] ,
  "mtmailer" : [ "internet-dynamo.png" , "http://www.mujica.com/" ] ,
  "moto-ezx" : [ "moto-ezx.png" , "http://www.motorola.com/" ] ,
  "misk.com" : [ "misk_com.png" , "http://www.misk.com/" ] ,
  "microdot" : [ "microdot.png" , "http://www.vapor.com/md1/" ] ,
  "meetlady" : [ "meetlady.png" , "http://meetlady.ru/" ] ,
  "medianet" : [ "clubinternet.png" , "http://www.club-internet.fr/" ] ,
  "mailroom" : [ "mailroom.png" , "http://www.sierrasol.com/" ] ,
  "mailgust" : [ "mailgust.png" , "http://www.mailgust.org/" ] ,
  "mailgate" : [ "mailgate.png" , "http://www.newscenterx.de/products/MailGate/" ] ,
  "mailer::" : [ "gossamer.png" , "http://www.gossamer-threads.com/scripts/webmail/" ] ,
  "mailcast" : [ "mailcast.png" , "http://www.atwww.com/page.asp?PartId=9" ] ,
  "mailboot" : [ "mailboot.png" , "http://mboot.pl/" ] ,
  "mail2000" : [ "mail2000.png" , "http://groups.yahoo.com/group/tmail2000/" ] ,
  "mahogany" : [ "mahogany.png" , "http://mahogany.sourceforge.net/" ] ,
  "mygate/" : [ "mygate.png" , "http://barin.com.ua/" ] ,
  "musashi" : [ "musashi.png" , "http://www.sonosoft.com/" ] ,
  "mp3real" : [ "mp3real.png" , "http://www.mp3real.ru/" ] ,
  "mopshop" : [ "mopshop.png" , "http://www.mopshop.de/" ] ,
  "mesnews" : [ "mesnews.png" , "http://www.mesnews.net/" ] ,
  "marco -" : [ "marco.png" , "http://www.tensid.ch/" ] ,
  "manitou" : [ "manitou.png" , "http://www.manitou-mail.org/" ] ,
  "mamabuy" : [ "mamabuy.png" , "http://www.mamabuy.de/" ] ,
  "mailout" : [ "mailout.png" , "http://www.mailout.com/" ] ,
  "mailman" : [ "mailman.png" , "http://www.list.org/" ] ,
  "mailit!" : [ "mailit.png" , "http://www.riverweb.com/modules/mailit/" ] ,
  "mailist" : [ "sharp-mailist.png" , "http://www.sharp.co.jp/" ] ,
  "mailbee" : [ "mailbee.png" ] ,
  "mail602" : [ "software602.png" , "http://www.software602.com/" ] ,
  "mail.bg" : [ "mail_bg.png" , "http://www.mail.bg/" ] ,
  "macsoup" : [ "macsoup.png" , "http://home.snafu.de/stk/macsoup/" ] ,
  "myblog" : [ "myblog.png" , "http://www.myblog.de/" ] ,
  "momail" : [ "momail.png" , "http://www.momail.de/" ] ,
  "modest" : [ "modest.png" , "http://modest.garage.maemo.org/" ] ,
  "marlin" : [ "marlin.png" , "http://www.marlin.de/" ] ,
  "mailup" : [ "mailup_it.png" , "http://www.mailup.it/" ] ,
  "macbay" : [ "macbay.png" , "http://www.macbay.de/" ] ,
  "mupad" : [ "mupad.png" , "http://www.mupad.com/" ] ,
  "mscrm" : [ "ms_crm.png" , "http://www.microsoft.com/crm/" ] ,
  "monit" : [ "monit.png" , "http://mmonit.com/monit/" ] ,
  "mmail" : [ "mmail.png" , "http://homepage1.nifty.com/kem_t/" ] ,
  "mixxt" : [ "mixxt.png" , "http://www.mixxt.net/" ] ,
  "mieze" : [ "mieze.png" , "http://www.dietmar-plassmann.de/mieze.html" ] ,
  "mambo" : [ "mambo.png" , "http://mambo-developer.org/" ] ,
  "magix" : [ "magix.png" , "http://www.magix.com/" ] ,
  "mybb" : [ "mybb.png" , "http://www.mybboard.net/" ] ,
  "mutt" : [ "mutt.png" , "http://www.mutt.org/" ] ,
  "miva" : [ "miva.png" , "http://www.miva.com/" ] ,
  "myeo" : [ "myeo.png" , "http://www.myeo.net/" ] ,
  "mxm-" : [ "mxm.png" , "http://www.m--x--m.net/" ] ,
  "mew " : [ "mew.png" , "http://www.mew.org/" ] ,
  "mbm " : [ "maxbulk-mailer.png" , "http://www.maxprog.com/site/software/internet-marketing/mass-bulk-emailer_sheet_de.php" ] ,
  "msn" : [ "msn.png" , "http://www.msn.com/" ] ,
  "mh " : [ "gnu.png" , "http://www.gnu.org/software/mailutils/" ] ,
}
