dispMUA.arDispMUAAllocation["x"] =
{
  "xtreeme followupxpert" : [ "xtreeme.png" , "http://www.xtreeme.com/followupxpert/" ] ,
  "xmpp-smtp-transport" : [ "xmpp-smtp.png" , "http://gorila.netlab.cz/jabber.html" ] ,
  "xinnet.com webmail" : [ "xinnet_com.png" , "http://www.xinnet.com/" ] ,
  "xtreeme mailxpert" : [ "xtreeme.png" , "http://www.xtreeme.com/mailxpert/" ] ,
  "ximian evolution" : [ "evolution.png" , "http://www.gnome.org/projects/evolution/" ] ,
  "xp2 (crosspoint" : [ "crosspoint_xp2.png" , "http://xp2.de/" ] ,
  "xtenit mailer" : [ "xtenit.png" , "http://www.xtenit.com/" ] ,
  "xp framework" : [ "xpframework.png" , "http://xp-framework.net/" ] ,
  "x-php-script" : [ "php.png" , "http://www.php.net/" ] ,
  "x-email diag" : [ "xerox.png" , "http://www.xerox.com/" ] ,
  "xpertmailer" : [ "xpertmailer.png" , "http://www.xpertmailer.com/" ] ,
  "xmltomime" : [ "yandex_ru.png" , "http://www.yandex.ru/" ] ,
  "xanga.com" : [ "xanga.png" , "http://www.xanga.com/" ] ,
  "x-mailer" : [ "x-mailer.png" , "http://www.x-mailer.info/" ] ,
  "xananews" : [ "xananews.png" , "http://www.wilsonc.demon.co.uk/xananews.htm" ] ,
  "xs2mail" : [ "xs2mail.png" , "http://www.xs2mail.com/" ] ,
  "xanario" : [ "xanario_de.png" , "http://www.xanario.de/" ] ,
  "x-sharp" : [ "sharp.png" , "http://www.sharp.co.jp/" ] ,
  "x-point" : [ "x-point.png" ] ,
  "xqmail" : [ "xqmail.png" , "http://www.xqueue.com/" ] ,
  "xmitip" : [ "xmitip.png" , "http://www.lbdsoftware.com/xmitip.html" ] ,
  "xfmail" : [ "xfmail.png" , "http://xfmail.slappy.org/" ] ,
  "xe.com" : [ "xe_com.png" , "http://www.xe.com/" ] ,
  "xnntp" : [ "xnntp.png" , "http://www.edv-consulting-berlin.de/Xnntp/" ] ,
  "xnews" : [ "xnews.png" , "http://xnews.newsguy.com/" ] ,
  "xmail" : [ "xmail.png" , "http://lestang.org/" ] ,
  "xerox" : [ "xerox.png" , "http://www.xerox.com/" ] ,
  "xpn/" : [ "xpn.png" , "http://xpn.altervista.org/" ] ,
  "xpm4" : [ "xpm.png" , "http://www.xpertmailer.com/" ] ,
  "xpm3" : [ "xpm.png" , "http://www.xpertmailer.com/" ] ,
  "xpm2" : [ "xpm.png" , "http://www.xpertmailer.com/" ] ,
  "xrn" : [ "xrn.png" , "http://www.mit.edu/people/jik/software/xrn.html" ] ,
}
