dispMUA.arDispMUAAllocation["n"] =
{
  "nec personal communicator mobile gear" : [ "nec-mobilegear.png" , "http://www.nec.co.jp/press/en/9803/1101.html" ] ,
  "notonebit.com simple mailer" : [ "notonebit_com.png" , "http://www.notonebit.com/" ] ,
  "newsletter.virtual-image.de" : [ "virtual-image_de.png" , "http://www.virtual-image.de/" ] ,
  "network solutions webmail" : [ "networksolutions.png" , "http://www.networksolutions.com/" ] ,
  "nero serial number mailer" : [ "nero.png" , "http://www.nero.com/" ] ,
  "netikus.net eventsentry" : [ "eventsentry.png" , "http://www.eventsentry.com/" ] ,
  "netmail modweb module" : [ "novell.png" , "http://www.novell.com/coolsolutions/netmail/" ] ,
  "nexus desktop client" : [ "aol.png" , "http://www.aol.com/" ] ,
  "nvsendmail utility" : [ "bakbone.png" , "http://www.bakbone.com/" ] ,
  "nuralstorm webmail" : [ "nuralstorm.png" , "http://www.nuralstorm.net/" ] ,
  "network automation" : [ "networkautomation_com.png" , "http://www.networkautomation.com/" ] ,
  "netangels helpdesk" : [ "netangels_ru.png" , "http://www.netangels.ru/" ] ,
  "nbb-rekenprogramma" : [ "nbb-rekenprogramma.png" ] ,
  "navigon newsmailer" : [ "navigon.png" , "http://www.navigon.com/" ] ,
  "newsletter genius" : [ "newsletter_genius.png" ] ,
  "nateon web mailer" : [ "nateon.png" , "http://nateonweb.nate.com/en/" ] ,
  "novell groupwise" : [ "groupwise.png" , "http://www.novell.com/products/groupwise/" ] ,
  "ni-mailer-skript" : [ "ni-mailer.png" , "http://www.n-image.com/" ] ,
  "newsletterscript" : [ "coder-world.png" , "http://www.coder-world.de/cw/seite__pagewebdesignnl.html" ] ,
  "nettoolworks.net" : [ "nettoolworks.png" , "http://www.nettoolworks.com/" ] ,
  "netfirms mailing" : [ "netfirms_com.png" , "http://www.netfirms.com/" ] ,
  "neotonic trakken" : [ "neotonic.png" , "http://google.about.com/od/n/g/neotonic.htm" ] ,
  "neocast@messager" : [ "ispirit.png" , "http://www.neocast.co.kr/" ] ,
  "nomad mime mail" : [ "nomad_mimemail.png" , "http://www.developarts.com/nomad_mimemail" ] ,
  "nms - 1:1 mail!" : [ "nms.png" ] ,
  "nic.at registry" : [ "nic_at.png" , "http://www.nic.at/" ] ,
  "nexus mime mail" : [ "nexus_mimemail.png" , "http://www.developarts.com/nomad_mimemail" ] ,
  "nero newsletter" : [ "nero.png" , "http://www.nero.com/" ] ,
  "namesco webmail" : [ "namesco-webmail.png" , "http://www.names.co.uk/webmail.html" ] ,
  "newsletter pro" : [ "newsletter_pro.png" , "http://www.aborange.de/products/newsletter.php" ] ,
  "nwp mailrelay" : [ "nwp.png" , "http://www.netzwerkplan.de/" ] ,
  "newswatcher-x" : [ "newswatcher-x.png" , "http://www.electricfish.com/products/NewsWatcherX/" ] ,
  "newsoffice.de" : [ "newsoffice_de.png" , "http://www.newsoffice.de/" ] ,
  "nettalk email" : [ "nettalk.png" ] ,
  "neo.pl mailer" : [ "neo_pl.png" , "http://neo.pl/" ] ,
  "nxnewsletter" : [ "nexum.png" , "http://www.nexum.de/" ] ,
  "null webmail" : [ "nulllogic.png" , "http://nullwebmail.sourceforge.net/webmail/" ] ,
  "nms formmail" : [ "nms-formmail.png" ] ,
  "notebook.de" : [ "notebook_de.png" , "http://www.notebook.de/" ] ,
  "nextmail.ru" : [ "nextmail.png" , "http://nextmail.ru/" ] ,
  "newzcrawler" : [ "newzcrawler.png" ] ,
  "newsman pro" : [ "newsman_pro.png" , "http://www.newsmanpro.com/" ] ,
  "newsleecher" : [ "newsleecher.png" , "http://www.newsleecher.com" ] ,
  "newscoaster" : [ "newscoaster.png" , "http://newscoaster.tripod.com/" ] ,
  "news xpress" : [ "news_xpress.png" ] ,
  "naukri-mail" : [ "naukri_com.png" , "http://www.naukri.com/" ] ,
  "nustep cms" : [ "nustep_net.png" , "http://www.nustep.net/cms" ] ,
  "nomad news" : [ "nomadnews.png" , "http://www.nomadnews.com" ] ,
  "nichost.ru" : [ "nic_ru.png" , "http://hosting.nic.ru/" ] ,
  "newsportal" : [ "newsportal.png" , "http://amrhein.eu/newsportal" ] ,
  "news rover" : [ "newsrover.png" , "http://www.newsrover.com/" ] ,
  "netcologne" : [ "netcologne.png" , "http://www.netcologne.de/" ] ,
  "nana-gnus/" : [ "gnus.png" , "http://gnus.org/" ] ,
  "ngtmailer" : [ "ngtmailer.png" , "http://www.ngt.no/" ] ,
  "newshound" : [ "newshound.png" , "http://shorelinesoftware.com/" ] ,
  "netangels" : [ "netangels_net.png" , "http://www.netangels.net/" ] ,
  "nyt-post" : [ "new_york_times.png" ] ,
  "nwebmail" : [ "nwebmail.png" , "http://nwebmail.sourceforge.net/" ] ,
  "noworyta" : [ "noworyta.png" ] ,
  "noson.it" : [ "noscon_it.png" , "http://listserver.noscon.it/" ] ,
  "newstap/" : [ "apple_appstore.png" , "http://sourceforge.net/projects/newstap" ] ,
  "netscape" : [ "netscape.png" , "http://mailnews.netscape.com/releases" ] ,
  "netfront" : [ "netfront.png" , "http://www.access-company.com/products/mobile_solutions/netfrontmobile/" ] ,
  "nourish" : [ "nourish.png" , "http://nouri.sh/" ] ,
  "newzbin" : [ "newzbin.png" , "http://www.newzbin.com/" ] ,
  "newspro" : [ "newspro.png" ] ,
  "newsbin" : [ "newsbin.png" , "http://www.newsbin.com/" ] ,
  "netpion" : [ "netpion.png" , "http://www.netpathy.com/products11.html" ] ,
  "netflix" : [ "netflix.png" , "http://www.netflix.com/" ] ,
  "netcat/" : [ "netcat.png" , "http://netcat.sourceforge.net/" ] ,
  "netcat " : [ "netcat.png" , "http://netcat.sourceforge.net/" ] ,
  "neomail" : [ "neomail.png" , "http://open-i.co.jp/html/product_01.html" ] ,
  "need.bg" : [ "need_bg.png" , "http://www.need.bg/" ] ,
  "ntmail" : [ "gordano_ms.png" , "http://www.gordano.com/kb.htm?q=1582" ] ,
  "nlsend" : [ "defacto.software.png" , "http://defacto-software.de/" ] ,
  "neu.de" : [ "neu_de.png" , "http://www.neu.de/" ] ,
  "neobox" : [ "neobox.png" , "http://www.neobox.net/" ] ,
  "nmail" : [ "nmail.png" , "http://passkorea.net/" ] ,
  "naja/" : [ "naja.png" , "http://www.keyphrene.com/products/naja/" ] ,
  "npop" : [ "npop.png" , "http://www.nakka.com/soft/npop/" ] ,
  "nocc" : [ "nocc.png" ] ,
  "nmh-" : [ "nmh.png" , "http://www.nongnu.org/nmh/" ] ,
  "nmh " : [ "nmh.png" , "http://www.nongnu.org/nmh/" ] ,
  "nemo" : [ "nemo.png" , "http://groups.google.com/group/nemox" ] ,
  "nail" : [ "nail.png" , "http://nail.sourceforge.net/" ] ,
  "nu/" : [ "nusphere.png" , "http://www.nusphere.com/" ] ,
  "nn/" : [ "nn.png" , "http://www.nndev.org/" ] ,
  "nn " : [ "nn.png" , "http://www.nndev.org/" ] ,
}
