dispMUA.arDispMUAAllocation["j"] =
{
  "jam - just a mailer" : [ "perl-jam.png" , "http://cpan.uwinnipeg.ca/dist/JaM" ] ,
  "just send a mail" : [ "justsendamail.png" , "http://powzone.com/" ] ,
  "jetbrains omea" : [ "omea.png" , "http://www.jetbrains.com/omea/" ] ,
  "jax newsletter" : [ "jax-newsletter.png" , "http://www.jtr.de/scripting/php/newsletter/" ] ,
  "jfbox webmail" : [ "jfbox_webmail.png" , "http://www.jfbox.com/" ] ,
  "janrufmonitor" : [ "janrufmonitor.png" , "http://www.janrufmonitor.de/" ] ,
  "jobserve-xss" : [ "jobserve.png" , "http://www.jobserve.com/" ] ,
  "jgs-mailing" : [ "jgs-xa.png" , "http://www.jgs-xa.de/" ] ,
  "jobleads.de" : [ "jobleads_de.png" , "http://www.jobleads.de/" ] ,
  "jana-server" : [ "jana.png" , "http://www.janaserver.de/" ] ,
  "joyfulnote" : [ "joyfulnote.png" , "http://www.kent-web.com/bbs/joyful.html" ] ,
  "jonapot.hu" : [ "netfactory_hu.png" , "http://www.netfactory.hu/" ] ,
  "jobletter " : [ "jobanzeiger.png" , "http://www.jobanzeiger.de/" ] ,
  "jed/timber" : [ "timber.png" , "http://www.chiark.greenend.org.uk/~sgtatham/timber.html" ] ,
  "jpvmailer" : [ "jpvmailer.png" , "http://www.ottorey.com.ar/jpvmailer.htm" ] ,
  "jaw::mail" : [ "jawmail.png" , "http://www.jawmail.org/" ] ,
  "java-mail" : [ "java.png" , "http://java.sun.com/products/javamail/" ] ,
  "java mail" : [ "java.png" , "http://java.sun.com/products/javamail/" ] ,
  "jet.mail" : [ "jet-mail.png" , "http://www.jetmail.pl/" ] ,
  "javamail" : [ "java.png" , "http://java.sun.com/products/javamail/" ] ,
  "jsvmail" : [ "shuriken_pro.png" , "http://www.justsystems.com/jp/products/shuriken/" ] ,
  "jawmail" : [ "jawmail.png" , "http://www.jawmail.org/" ] ,
  "jamaila" : [ "jamaila.png" , "http://www.javakaffee.de/jamaila/" ] ,
  "jffnms" : [ "jffnms.png" , "http://www.jffnms.org/" ] ,
  "jbmail" : [ "jbmail.png" , "http://jbmail.pc-tools.net/" ] ,
  "jaring" : [ "jaring.png" , "http://www.jaring.my/" ] ,
  "jamail" : [ "jamail.png" , "http://www.jamail.de/" ] ,
  "jmail" : [ "dimac.png" , "http://www.dimac.net/" ] ,
  "juno" : [ "juno.png" , "http://webmail.juno.com/" ] ,
}
