pref("extensions.smartfilters.mailing.list.pattern", "lists.%");
pref("extensions.smartfilters.robot.pattern", "robots.%");
pref("extensions.smartfilters.subject.pattern", "%");
pref("extensions.smartfilters.subject.ignore", "FW RE a at the");
pref("extensions.smartfilters.backend", "imap folders");
pref("extensions.smartfilters.filter.1", "mailing list");
pref("extensions.smartfilters.filter.2", "robot");
pref("extensions.smartfilters.filter.3", "subject");
pref("extensions.smartfilters.max.emails.count", 1000);
pref("extensions.smartfilters.threshold", 5);
pref("extensions.smartfilters.last.date", "");
pref("extensions.smartfilters.daily", true);
