pref("extensions.smartfilters.mailing.list.pattern", "lists.%u");
pref("extensions.smartfilters.robot.pattern", "robots.%u");
pref("extensions.smartfilters.subject.pattern", "%k");
pref("extensions.smartfilters.subject.ignore", "FW RE a at the");
pref("extensions.smartfilters.backend", "imap folders");
pref("extensions.smartfilters.filter.1", "mailing list");
pref("extensions.smartfilters.filter.2", "robot");
pref("extensions.smartfilters.filter.3", "subject");
pref("extensions.smartfilters.max.emails.count", 1000);
pref("extensions.smartfilters.threshold", 5);
